/**
 * PM2 Ecosystem Configuration
 * IT Control Enterprise Dashboard
 *
 * Deploy: pm2 start ecosystem.config.js --env production
 * Reload:  pm2 reload it-dashboard
 * Stop:    pm2 stop it-dashboard
 * Logs:    pm2 logs it-dashboard
 */

module.exports = {
  apps: [
    {
      name: 'it-dashboard',

      // Standalone build entry point generated by `next build`
      script: '.next/standalone/server.js',

      instances: 1,           // t3.medium has 2 vCPUs; 1 instance leaves headroom for GLPI + n8n
      exec_mode: 'fork',      // fork is lighter than cluster for a single instance

      // Environment: production
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOSTNAME: '127.0.0.1', // bind only to localhost; Apache proxies externally
      },

      // Environment: development (for local testing)
      env_development: {
        NODE_ENV: 'development',
        PORT: 3000,
      },

      // Logging
      out_file: '/var/log/pm2/it-dashboard-out.log',
      error_file: '/var/log/pm2/it-dashboard-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,

      // Auto-restart on crash
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 3000,

      // Memory guard – restart if process exceeds 400 MB
      // (leaves memory for GLPI + n8n on t3.medium with 4 GB RAM)
      max_memory_restart: '400M',

      // Watch production build changes (disabled; handled by deploy script)
      watch: false,

      // Graceful shutdown
      kill_timeout: 5000,
      listen_timeout: 10000,
      shutdown_with_message: true,
    },
  ],
}
